"""
BF16 Accumulator Safety Plots — Realistic Distribution
Data source: bf16_acc_noise_budget.csv  (generated by BF16AccLossAnalysisTest.scala)

Activation: N(0, σ=3.62) + 6 positive-only outliers up to 4384  (real down_proj stats)
Weight:     N(0, σ=0.0124)  (real down_proj weight std)
Both inputs MX-quantized in blocks of 32 before accumulation.

Figures generated:
  bf16_acc_realistic_safety.png   — 3-panel safety proof  (scatter / bars / heatmap)
  bf16_acc_realistic_pipeline.png — 2-panel pipeline breakdown  (stages / S3 vs S4)
  bf16_acc_realistic_blocksize.png — block-size sensitivity for tightest INT8 configs
"""

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ── Load data ────────────────────────────────────────────────────────────────
df = pd.read_csv('bf16_acc_noise_budget.csv')
df['mac_pair'] = df['typeA'] + '×' + df['typeB']

MAC_PAIRS = [
    'E5M2×E5M2', 'E4M3×E4M3', 'E3M2×E3M2',
    'E5M2×E4M3',
    'INT8×E5M2', 'INT8×E4M3', 'INT8×INT8',
]
SCALES      = ['UE8M0', 'UE6M2', 'UE5M3', 'UE4M4']
SCALE_COLOR = {'UE8M0': '#1976D2', 'UE6M2': '#388E3C', 'UE5M3': '#F57C00', 'UE4M4': '#7B1FA2'}
SCALE_MARK  = {'UE8M0': 'o',       'UE6M2': 's',       'UE5M3': '^',       'UE4M4': 'D'}
TENSOR_MARK = {64: 'o', 256: 's'}
TENSOR_LINE = {64: '--', 256: '-'}

# Worst-case (minimum margin) over blockSize for each (mac_pair, scale, tensorSize)
df_min = df.groupby(['mac_pair', 'scaleType', 'tensorSize', 'K', 'accMantBits']).agg(
    margin_dB=('margin_dB', 'min'),
    SQNR_S1_dB=('SQNR_S1_dB', 'mean'),
    SQNR_S2_dB=('SQNR_S2_dB', 'mean'),
    SQNR_S3_dB=('SQNR_S3_dB', 'mean'),
    SQNR_S4_dB=('SQNR_S4_dB', 'min'),   # worst S4 (smallest) for margin headline
    SQNR_total_dB=('SQNR_total_dB', 'mean'),
).reset_index()

# Absolute worst over tensorSize too (for single-value heatmap)
df_worst = df_min.groupby(['mac_pair', 'scaleType']).agg(
    margin_dB=('margin_dB', 'min'),
    SQNR_S3_dB=('SQNR_S3_dB', 'mean'),
    SQNR_S4_dB=('SQNR_S4_dB', 'min'),
    accMantBits=('accMantBits', 'max'),
).reset_index()

# ─────────────────────────────────────────────────────────────────────────────
# Figure 1: Two-panel safety proof  (bars + heatmap)
# ─────────────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle(
    'BF16 Accumulator Safety Proof — Realistic Input Distribution\n'
    'Activation: N(0, σ=3.62) + outliers up to 4384   |   Weight: U(−1, 1)   |   '
    'Inputs MX-quantized in blocks of 32\n'
    'margin = SQNR_S3 (BF16 truncation) − SQNR_S4 (requantization)   →   all positive = SAFE',
    fontsize=10, fontweight='bold', y=1.03
)

# ── (a) Margin bars — worst case (min over blockSize × tensorSize) ────────────
ax = axes[0]
x     = np.arange(len(MAC_PAIRS))
width = 0.19

for i, sc in enumerate(SCALES):
    margins = []
    for mp in MAC_PAIRS:
        row = df_worst[(df_worst['mac_pair'] == mp) & (df_worst['scaleType'] == sc)]
        margins.append(float(row['margin_dB'].values[0]) if len(row) else 0.0)
    offset = (i - 1.5) * width
    bars = ax.bar(x + offset, margins, width, label=sc,
                  color=SCALE_COLOR[sc], alpha=0.88, edgecolor='white', linewidth=0.5)
    for bar, val in zip(bars, margins):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
                f'{val:.0f}', ha='center', va='bottom', fontsize=7, color='#333')

ax.axhline(0, color='red', lw=1.5, ls='--', label='Safety boundary (0 dB)', zorder=3)
ax.set_xticks(x)
ax.set_xticklabels(MAC_PAIRS, rotation=30, ha='right', fontsize=9)
ax.set_ylabel('Safety margin  =  SQNR_S3 − SQNR_S4  (dB)', fontsize=10)
ax.set_title('(a) Worst-case safety margin per MAC pair × scale type\n'
             'min over blockSize ∈ {8, 16, 32} × tensor ∈ {64×64, 256×256}',
             fontsize=9.5, fontweight='bold')
ax.legend(fontsize=9)
ax.grid(True, alpha=0.3, axis='y')
ax.set_ylim(bottom=0)

# ── (b) Heatmap of worst-case margin ─────────────────────────────────────────
ax = axes[1]
heat = np.zeros((len(MAC_PAIRS), len(SCALES)))
for i, mp in enumerate(MAC_PAIRS):
    for j, sc in enumerate(SCALES):
        row = df_worst[(df_worst['mac_pair'] == mp) & (df_worst['scaleType'] == sc)]
        heat[i, j] = float(row['margin_dB'].values[0]) if len(row) else 0.0

im = ax.imshow(heat, cmap='YlGn', aspect='auto', vmin=0, vmax=heat.max() + 5)
cbar = plt.colorbar(im, ax=ax, shrink=0.85)
cbar.set_label('Margin (dB)', fontsize=8)

ax.set_xticks(range(len(SCALES)))
ax.set_xticklabels(SCALES, fontsize=8.5)
ax.set_yticks(range(len(MAC_PAIRS)))
ax.set_yticklabels(MAC_PAIRS, fontsize=8.5)

for i in range(len(MAC_PAIRS)):
    for j in range(len(SCALES)):
        val = heat[i, j]
        color = 'white' if val > heat.max() * 0.6 else 'black'
        ax.text(j, i, f'+{val:.1f}', ha='center', va='center',
                fontsize=8.5, fontweight='bold', color=color)

ax.set_title('(b) Safety margin heatmap (dB)\n'
             'worst case: min over blockSize × tensorSize   |   all green = all SAFE',
             fontsize=9.5, fontweight='bold')

plt.tight_layout()
plt.savefig('bf16_acc_realistic_safety.png', dpi=150, bbox_inches='tight')
plt.close()
print("Saved bf16_acc_realistic_safety.png")

# ─────────────────────────────────────────────────────────────────────────────
# Figure 2: Pipeline noise breakdown
# ─────────────────────────────────────────────────────────────────────────────
STAGE_COLORS = {
    'SQNR_S1_dB': '#90CAF9',
    'SQNR_S2_dB': '#42A5F5',
    'SQNR_S3_dB': '#FF7043',
    'SQNR_S4_dB': '#EF5350',
}
STAGE_LABELS = {
    'SQNR_S1_dB': 'S1: FP32 rounding (~99 dB, negligible)',
    'SQNR_S2_dB': 'S2: Accumulation @ accM bits',
    'SQNR_S3_dB': 'S3: BF16 truncation  ← KEY',
    'SQNR_S4_dB': 'S4: Requantization  ← noise floor',
}

fig, axes = plt.subplots(1, 2, figsize=(18, 6))
fig.suptitle(
    'BF16 Accumulator — Pipeline Noise Budget  (Realistic Distribution)\n'
    'Activation: N(0,σ=3.62)+outliers≤4384   |   Weight: U(−1,1)   |   accM = AccPrecision.recommended',
    fontsize=10, fontweight='bold', y=1.02
)

# ── (d) All stages, UE8M0, worst tensor (256), blockSize=16 ──────────────────
ax = axes[0]
sub_d = df[(df['scaleType'] == 'UE8M0') & (df['tensorSize'] == 256) & (df['blockSize'] == 16)]
sub_d = sub_d.set_index('mac_pair').reindex(MAC_PAIRS)
stages = ['SQNR_S1_dB', 'SQNR_S2_dB', 'SQNR_S3_dB', 'SQNR_S4_dB']
x     = np.arange(len(MAC_PAIRS))
width = 0.18

for i, stage in enumerate(stages):
    vals      = sub_d[stage].values.astype(float)
    vals_plot = np.minimum(vals, 99.0)
    bars = ax.bar(x + (i - 1.5) * width, vals_plot, width,
                  label=STAGE_LABELS[stage], color=STAGE_COLORS[stage],
                  edgecolor='white', linewidth=0.5)
    for bar, v in zip(bars, vals_plot):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.5,
                f'{v:.0f}', ha='center', va='bottom', fontsize=6, rotation=90)

# annotate accMantBits below x-axis
for xi, mp in zip(x, MAC_PAIRS):
    row = sub_d.loc[mp]
    ax.text(xi, -8, f'accM={int(row["accMantBits"])}',
            ha='center', va='top', fontsize=7, color='#555', fontweight='bold')

# double-headed arrows showing S3>S4 margin
for xi, mp in zip(x, MAC_PAIRS):
    row = sub_d.loc[mp]
    s3 = min(float(row['SQNR_S3_dB']), 99.0)
    s4 = float(row['SQNR_S4_dB'])
    if s3 > s4 + 1:
        ax.annotate('', xy=(xi + 0.5 * width, s4 + 0.5),
                    xytext=(xi + 0.5 * width, s3 - 0.5),
                    arrowprops=dict(arrowstyle='<->', color='#B71C1C', lw=1.2))

ax.set_xticks(x)
ax.set_xticklabels(MAC_PAIRS, rotation=30, ha='right', fontsize=8.5)
ax.set_ylabel('SQNR (dB)', fontsize=10)
ax.set_title('(d) All pipeline stages — UE8M0 scale, tensor=256×256\n'
             'accM = AccPrecision.recommended  |  blockSize=16',
             fontsize=9, fontweight='bold')
ax.legend(fontsize=7.5, loc='upper right')
ax.grid(True, alpha=0.3, axis='y')
ax.set_ylim(-13, 108)

# ── (e) S3 vs S4 for all scales, tensor=256, blockSize=16 ────────────────────
ax = axes[1]
sub_e = df[(df['tensorSize'] == 256) & (df['blockSize'] == 16)]
x     = np.arange(len(MAC_PAIRS))
width = 0.10
group_gap = 0.02

for j, sc in enumerate(SCALES):
    sub_sc = sub_e[sub_e['scaleType'] == sc].set_index('mac_pair').reindex(MAC_PAIRS)
    s3_vals = np.minimum(sub_sc['SQNR_S3_dB'].values.astype(float), 99.0)
    s4_vals = sub_sc['SQNR_S4_dB'].values.astype(float)
    base    = (j - 1.5) * (2 * width + group_gap)
    ax.bar(x + base,         s3_vals, width, color=SCALE_COLOR[sc], alpha=0.9,
           label=f'{sc} — S3', edgecolor='white', linewidth=0.3)
    ax.bar(x + base + width, s4_vals, width, color=SCALE_COLOR[sc], alpha=0.45,
           hatch='//', edgecolor=SCALE_COLOR[sc], linewidth=0.5,
           label=f'{sc} — S4')

ax.set_xticks(x)
ax.set_xticklabels(MAC_PAIRS, rotation=30, ha='right', fontsize=8.5)
ax.set_ylabel('SQNR (dB)', fontsize=10)
ax.set_title('(e) S3 BF16 truncation (solid) vs S4 requant (hatched)\n'
             'tensor=256×256, blockSize=16  |  solid bar always taller → SAFE',
             fontsize=9, fontweight='bold')
ax.grid(True, alpha=0.3, axis='y')
ax.set_ylim(0, 75)

legend_handles = [mpatches.Patch(facecolor=SCALE_COLOR[sc], label=sc) for sc in SCALES]
solid   = mpatches.Patch(facecolor='grey',       label='Solid = S3 (BF16 trunc)')
hatched = mpatches.Patch(facecolor='grey', hatch='//', label='Hatched = S4 (requant)')
ax.legend(handles=legend_handles + [solid, hatched], fontsize=7.5, ncol=2, loc='upper right')

plt.tight_layout()
plt.savefig('bf16_acc_realistic_pipeline.png', dpi=150, bbox_inches='tight')
plt.close()
print("Saved bf16_acc_realistic_pipeline.png")

# ─────────────────────────────────────────────────────────────────────────────
# Figure 3: Block-size and tensor-size sensitivity
# Two-panel: left = margin vs blockSize for INT8 configs (tightest group)
#            right = margin vs tensorSize (K) for all scales, blockSize=16
# ─────────────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle(
    'BF16 Accumulator — Sensitivity Analysis\n'
    'Realistic Distribution: Activation N(0,σ=3.62)+outliers≤4384  |  Weight N(0,σ=0.0124)',
    fontsize=10, fontweight='bold', y=1.02
)

INT8_PAIRS = ['INT8×E5M2', 'INT8×E4M3', 'INT8×INT8']
FP8_PAIRS  = ['E5M2×E5M2', 'E4M3×E4M3', 'E5M2×E4M3']
BLOCK_SIZES   = [8, 16, 32]
TENSOR_SIZES  = [64, 256]
PAIR_COLORS   = {
    'E5M2×E5M2': '#1976D2', 'E4M3×E4M3': '#388E3C', 'E3M2×E3M2': '#43A047',
    'E5M2×E4M3': '#00ACC1',
    'INT8×E5M2': '#E53935', 'INT8×E4M3': '#FB8C00', 'INT8×INT8': '#8E24AA',
}
PAIR_MARKS = {
    'E5M2×E5M2': 'o', 'E4M3×E4M3': 's', 'E3M2×E3M2': 'D',
    'E5M2×E4M3': '^',
    'INT8×E5M2': 'o', 'INT8×E4M3': 's', 'INT8×INT8': '^',
}

# ── (f) Margin vs blockSize for UE8M0 scale, tensor=256 (worst K) ────────────
ax = axes[0]
sub_f  = df[(df['scaleType'] == 'UE8M0') & (df['tensorSize'] == 256)]
# Plot INT8 pairs with solid lines, FP8 pairs with dashed (to separate the groups visually)
for mp in INT8_PAIRS + FP8_PAIRS:
    sub_mp = sub_f[sub_f['mac_pair'] == mp].sort_values('blockSize')
    ls = '-' if mp in INT8_PAIRS else '--'
    lw = 1.8 if mp in INT8_PAIRS else 1.1
    ax.plot(sub_mp['blockSize'], sub_mp['margin_dB'],
            marker=PAIR_MARKS[mp], color=PAIR_COLORS[mp],
            ls=ls, lw=lw, markersize=7, label=mp)

ax.axhline(0, color='red', lw=1.5, ls='--', zorder=3)
ax.set_xticks(BLOCK_SIZES)
ax.set_xlabel('Output requant block size', fontsize=10)
ax.set_ylabel('Safety margin  =  SQNR_S3 − SQNR_S4  (dB)', fontsize=10)
ax.set_title('(f) Margin vs blockSize  —  UE8M0, tensor=256×256\n'
             'INT8 pairs (solid) are tightest; all > 0 dB = SAFE',
             fontsize=9, fontweight='bold')
ax.legend(fontsize=8, loc='upper right', ncol=2)
ax.grid(True, alpha=0.3)

# ── (g) Margin vs tensorSize for UE8M0, blockSize=16 — all pairs ─────────────
ax = axes[1]
sub_g = df[(df['scaleType'] == 'UE8M0') & (df['blockSize'] == 16)]
for mp in INT8_PAIRS + FP8_PAIRS:
    sub_mp = sub_g[sub_g['mac_pair'] == mp].sort_values('tensorSize')
    ls = '-' if mp in INT8_PAIRS else '--'
    lw = 1.8 if mp in INT8_PAIRS else 1.1
    ax.plot(sub_mp['tensorSize'], sub_mp['margin_dB'],
            marker=PAIR_MARKS[mp], color=PAIR_COLORS[mp],
            ls=ls, lw=lw, markersize=7, label=mp)

ax.axhline(0, color='red', lw=1.5, ls='--', zorder=3)
ax.set_xticks(TENSOR_SIZES)
ax.set_xticklabels(['64×64\n(K=16)', '256×256\n(K=64)'])
ax.set_xlabel('Tensor size  (inner dimension → K accumulation cycles)', fontsize=10)
ax.set_ylabel('Safety margin  =  SQNR_S3 − SQNR_S4  (dB)', fontsize=10)
ax.set_title('(g) Margin vs tensor size  —  UE8M0, blockSize=16\n'
             'Larger K uses higher accMantBits → S3 stable; margin stays positive',
             fontsize=9, fontweight='bold')
ax.legend(fontsize=8, loc='upper right', ncol=2)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('bf16_acc_realistic_blocksize.png', dpi=150, bbox_inches='tight')
plt.close()
print("Saved bf16_acc_realistic_blocksize.png")

# ─────────────────────────────────────────────────────────────────────────────
# Print summary table
# ─────────────────────────────────────────────────────────────────────────────
print()
print('=' * 90)
print('SUMMARY: worst-case margin (min over blockSize × tensorSize)')
print('  Distribution: Activation N(0,σ=3.62)+outliers≤4384  |  Weight N(0,σ=0.0124)')
print('=' * 90)
pivot = df_worst.pivot_table(index='mac_pair', columns='scaleType', values='margin_dB')
pivot = pivot.reindex(index=MAC_PAIRS, columns=SCALES)
print(pivot.round(1).to_string())
print()
worst_row = df_worst.loc[df_worst['margin_dB'].idxmin()]
print(f"Worst-case margin: {df_worst['margin_dB'].min():.1f} dB"
      f"  ({worst_row['mac_pair']}, {worst_row['scaleType']})")
print("All SAFE:", (df_worst['margin_dB'] > 0).all())
print('=' * 90)
