
# ── Synopsys Design Compiler synthesis script ─────────────────────────────────
# Generated by BFP_PE_synth.ipynb
# CONFIG : INT8_E2M1_UE8M0_vec1
# RTL    : /users/students/r0927191/Documents/chisel/SNAX-Chisel/hw/chisel_acc/generated/test_fused_dot/INT8_E2M1_UE8M0_vec1/BFP_PE.sv

set DESIGN_NAME  "BFP_PE"
set RTL_FILE     "/users/students/r0927191/Documents/chisel/SNAX-Chisel/hw/chisel_acc/generated/test_fused_dot/INT8_E2M1_UE8M0_vec1/BFP_PE.sv"
set PDK_ROOT     "/esat/micas_raid/users/h05d4a_students/conda-env/share/pdk"
set TAG          "260327-013456_INT8_E2M1_UE8M0_vec1"

# ── Technology libraries ──────────────────────────────────────────────────────
set _lib_file_str [exec find $STD_CELL_LIB_ROOT -name "*.lib" -maxdepth 4]
set search_path  [concat $search_path [list /esat/micas_raid/users/h05d4a_students/conda-env/share/pdk/standard_cell_libraries]]
set target_library  [split [string trim $_lib_file_str]"\n"]
set link_library    [concat "*" $target_library]

puts "Using [llength $target_library] library file(s):"
foreach lib $target_library { puts "  $lib" }

# ── Output directories ────────────────────────────────────────────────────────
set RESULTS_DIR "./runs/$TAG/results"
set REPORTS_DIR "./runs/$TAG/reports"
file mkdir $RESULTS_DIR
file mkdir $REPORTS_DIR

# ── Read & elaborate ─────────────────────────────────────────────────────────
analyze -format sverilog $RTL_FILE
elaborate $DESIGN_NAME
current_design $DESIGN_NAME
link

# ── Constraints ───────────────────────────────────────────────────────────────
create_clock -period 1.0 -name clk [get_ports clock]
set_input_delay  0 -clock clk [all_inputs]
set_output_delay 0 -clock clk [all_outputs]

# ── Compile ───────────────────────────────────────────────────────────────────
compile_ultra

# ── Reports ───────────────────────────────────────────────────────────────────
report_area    -hierarchy > $REPORTS_DIR/area.rpt
report_timing  -max_paths 10 > $REPORTS_DIR/timing.rpt
report_power   > $REPORTS_DIR/power.rpt
report_cell    > $REPORTS_DIR/cells.rpt

# ── Write netlist ─────────────────────────────────────────────────────────────
write -format verilog -hierarchy -output $RESULTS_DIR/$DESIGN_NAME\_netlist.v
write_sdf $RESULTS_DIR/$DESIGN_NAME.sdf

puts "\n[SUCCESS] Synthesis complete: $TAG"
exit
