# OpenSTA power analysis script
# Generated by sta.sh — do not edit manually; edit sta/templates/power.tcl instead.

# ---- Technology library ----
read_liberty /users/micas/micas/design/tsmc28hpcplus/standard_cell_libraries/tcbn28hpcplusbwp30p140-set/tcbn28hpcplusbwp30p140_190a_FE/TSMCHOME/digital/Front_End/timing_power_noise/NLDM/tcbn28hpcplusbwp30p140_180a/tcbn28hpcplusbwp30p140tt0p9v25c.lib


# ---- Read gate-level netlist ----
read_verilog /users/students/r0927191/Documents/chisel/SNAX-Chisel/hw/chisel_acc/Backend/OS_framework_CL/syn/outputs/INT8_INT8_UE8M0_vec4/BFP_PE_mapped.v
link_design BFP_PE

# ---- Clock definition ----
# sta.sh activates one of the two lines based on CLOCK_PORT in config.sh.
# REAL_CLOCK: clock on a physical port (sequential designs)
# VIRTUAL_CLOCK: no physical clock port (combinational designs)
create_clock [get_ports clock] -period 20.0000 -name CORE_CLK -waveform "0 10.0000"

# ---- SDC constraints (max_transition, max_fanout, clock uncertainty) ----
set_clock_uncertainty 0.025 -hold [get_clocks CORE_CLK]
set_clock_uncertainty 0.05 -setup [get_clocks CORE_CLK]
set_input_delay  0 -clock CORE_CLK [all_inputs]
set_output_delay 0 -clock CORE_CLK [all_outputs]
set_max_fanout 32 [current_design]
set_max_transition 0.250 [current_design]


# ---- Annotate switching activity from VCD ----
# strip_path = <tb_module>/<dut_instance>
# VCD was generated by sim-syn.sh (RTL or gate-level simulation).
read_vcd -scope tb_pt_bfp_pe/BFP_PE /users/students/r0927191/Documents/chisel/SNAX-Chisel/hw/chisel_acc/Backend/OS_framework_CL/sim-syn/vcd/INT8_INT8_UE8M0_vec4/BFP_PE_default.vcd

# ---- Timing analysis ----
report_checks -path_delay max -digits 4 > /users/students/r0927191/Documents/chisel/SNAX-Chisel/hw/chisel_acc/Backend/OS_framework_CL/sta/reports/INT8_INT8_UE8M0_vec4/timing_default.rpt
report_wns

# ---- Power analysis ----
# Flat total power report written to file; also echoed to terminal
report_power > /users/students/r0927191/Documents/chisel/SNAX-Chisel/hw/chisel_acc/Backend/OS_framework_CL/sta/reports/INT8_INT8_UE8M0_vec4/power_default.rpt
report_power

exit
