# OpenSTA power analysis script
# Generated by sta.sh — do not edit manually; edit sta/templates/power.tcl instead.

# ---- Technology library ----
read_liberty /users/micas/scuycken/Claude/RTL_LLM_Loop_v1.4/OpenSource/PDK/OpenROAD-flow-scripts/flow/platforms/nangate45/lib/NangateOpenCellLibrary_typical.lib


# ---- Read gate-level netlist ----
read_verilog /users/micas/scuycken/no_backup/OS_framework_CL/syn/outputs/run_001/mac_8bit_mapped.v
link_design mac_8bit

# ---- Clock definition ----
# sta.sh activates one of the two lines based on CLOCK_PORT in config.sh.
# REAL_CLOCK: clock on a physical port (sequential designs)
# VIRTUAL_CLOCK: no physical clock port (combinational designs)
create_clock [get_ports clk_i] -period 2.0000 -name CORE_CLK -waveform "0 1.0000"

# ---- SDC constraints (max_transition, max_fanout, clock uncertainty) ----
set_clock_uncertainty 0.025 -hold [get_clocks CORE_CLK]
set_clock_uncertainty 0.05 -setup [get_clocks CORE_CLK]
set_max_fanout 32 [current_design]
set_max_transition 0.250 [current_design]


# ---- Annotate switching activity from VCD ----
# strip_path = <tb_module>/<dut_instance>
# VCD was generated by sim-syn.sh (RTL or gate-level simulation).
read_vcd -scope tb_pt_mac_8bit/mac_8bit0 /users/micas/scuycken/no_backup/OS_framework_CL/sim-syn/vcd/run_001/mac_8bit_default.vcd

# ---- Power analysis ----
# Flat total power report written to file; also echoed to terminal
report_power > /users/micas/scuycken/no_backup/OS_framework_CL/sta/reports/run_001/power_default.rpt
report_power

exit
