# OpenSTA power analysis script
# Generated by sta.sh — do not edit manually; edit sta/templates/power.tcl instead.

# ---- Technology library ----
{READ_LIBERTY_CMDS}

# ---- Read gate-level netlist ----
read_verilog {PROJ_DIR}/syn/outputs/{RUN_ID}/{DESIGN_NAME}_mapped.v
link_design {DESIGN_NAME}

# ---- Clock definition ----
# sta.sh activates one of the two lines based on CLOCK_PORT in config.sh.
# REAL_CLOCK: clock on a physical port (sequential designs)
# VIRTUAL_CLOCK: no physical clock port (combinational designs)
{CLOCK_CMD}

# ---- SDC constraints (max_transition, max_fanout, clock uncertainty) ----
{SDC_CONSTRAINTS}

# ---- Annotate switching activity from VCD ----
# strip_path = <tb_module>/<dut_instance>
# VCD was generated by sim-syn.sh (RTL or gate-level simulation).
read_vcd -scope {TB_SIM}/{DESIGN_NAME}{VCD_INSTANCE_SUFFIX} {PROJ_DIR}/sim-syn/vcd/{RUN_ID}/{DESIGN_NAME}_{WORKLOAD}.vcd

# ---- Timing analysis ----
report_checks -path_delay max -digits 4 > {PROJ_DIR}/sta/reports/{RUN_ID}/timing_{WORKLOAD}.rpt
report_wns

# ---- Power analysis ----
# Flat total power report written to file; also echoed to terminal
report_power > {PROJ_DIR}/sta/reports/{RUN_ID}/power_{WORKLOAD}.rpt
report_power

exit
