# OpenSTA power analysis script — static mode (no VCD)
# Generated by sta.sh — do not edit manually; edit sta/templates/power_no_vcd.tcl instead.
#
# Used when SKIP_SIM=true.  Switching activity is estimated with a default 10% toggle rate
# rather than being annotated from a VCD.  Area and timing are unaffected.

# ---- Technology library ----
{READ_LIBERTY_CMDS}

# ---- Read gate-level netlist ----
read_verilog {PROJ_DIR}/syn/outputs/{RUN_ID}/{DESIGN_NAME}_mapped.v
link_design {DESIGN_NAME}

# ---- Clock definition ----
{CLOCK_CMD}

# ---- SDC constraints (max_transition, max_fanout, clock uncertainty) ----
{SDC_CONSTRAINTS}

# ---- Default switching activity (no VCD) ----
# 10% toggle rate on all inputs; internal nodes inferred from liberty tables.
set_power_activity -input 0.1
set_power_activity -input_port_toggle 0.1

# ---- Power analysis ----
report_power > {PROJ_DIR}/sta/reports/{RUN_ID}/power_{WORKLOAD}.rpt
report_power

exit
