// Power testbench for BFP_PE — auto-generated by gen_bfp_pe_tb.py
// io_op_a_i = 32 bits   io_op_b_i = 32 bits
// Do NOT edit manually — re-run gen_bfp_pe_tb.py to regenerate.
`timescale 1ns/1ps

module tb_pt_bfp_pe;

    // ---- Port mirrors ----
    logic              clock;
    logic              reset;
    logic [31:0]  io_op_a_i;
    logic [31:0]  io_op_b_i;
    logic [7:0]        io_share_exp_A_i;
    logic [7:0]        io_share_exp_B_i;
    logic              io_validIn;
    logic              io_resetAcc;
    logic              io_validOut;
    logic [31:0]       io_accOut;

    // ---- Clock generation ({CLK_HALF} filled by sim-syn.sh) ----
    always begin #({CLK_HALF}); clock = ~clock; end

    // ---- DUT instantiation ----
    // Instance name matches DESIGN_NAME so OpenSTA VCD scope resolves:
    //   -scope {TB_SIM}/{DESIGN_NAME}  →  tb_pt_bfp_pe/BFP_PE
    BFP_PE BFP_PE (
        .clock             (clock),
        .reset             (reset),
        .io_op_a_i         (io_op_a_i),
        .io_op_b_i         (io_op_b_i),
        .io_share_exp_A_i  (io_share_exp_A_i),
        .io_share_exp_B_i  (io_share_exp_B_i),
        .io_validIn        (io_validIn),
        .io_resetAcc       (io_resetAcc),
        .io_validOut       (io_validOut),
        .io_accOut         (io_accOut)
    );

    integer i;

    initial begin
        clock = 0;
        // BFP_PE uses active-high synchronous reset (Chisel default)
        reset = 1; io_op_a_i = 0; io_op_b_i = 0;
        io_share_exp_A_i = 0; io_share_exp_B_i = 0;
        io_validIn = 0; io_resetAcc = 0;

        $dumpfile("{PROJ_DIR}/sim-syn/vcd/{DIR_LOC_TEMP}/{DESIGN_NAME}_{WORKLOAD}.vcd");
        $dumpvars(0, tb_pt_bfp_pe);
        $dumpon;

        // ---- Reset: hold high for 4 cycles, then release ----
        repeat(4) @(posedge clock);
        reset = 0;
        // Clear accumulator once after reset
        io_resetAcc = 1;
        @(posedge clock);
        io_resetAcc = 0;

        // ---- Phase 1 — High-toggle: random inputs, validIn=1 ----
        // Exercises dynamic power at maximum toggle rate.
        io_validIn = 1;
        for (i = 0; i < 256; i = i + 1) begin
            io_op_a_i        = $urandom;
            io_op_b_i        = $urandom;
            io_share_exp_A_i = $urandom & 8'hFF;
            io_share_exp_B_i = $urandom & 8'hFF;
            @(posedge clock);
        end

        // ---- Phase 2 — Moderate-toggle: structured counter pattern ----
        // Deterministic pattern for reproducible power comparison.
        for (i = 0; i < 128; i = i + 1) begin
            io_op_a_i        = i[31:0];
            io_op_b_i        = ~i[31:0];
            io_share_exp_A_i = i[7:0];
            io_share_exp_B_i = ~i[7:0];
            @(posedge clock);
        end

        // ---- Phase 3 — Idle/leakage: fixed inputs, validIn=0 ----
        // Captures leakage + static power contribution.
        io_validIn       = 0;
        io_op_a_i        = 0;
        io_op_b_i        = 0;
        io_share_exp_A_i = 8'h7F;
        io_share_exp_B_i = 8'h7F;
        repeat(128) @(posedge clock);

        $dumpoff;
        $finish;
    end

endmodule
